application: good--job
version: v1
runtime: go
api_version: go1

default_expiration: "2s"

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
  secure: always

- url: /push.js
  static_files: js/push.js
  upload: js/push.js
  secure: always

- url: /(.*\.html)$
  static_files: html/\1
  upload: html/.\.html$
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /style
  static_dir: style
  secure: always

- url: /.*
  script: _go_app
  secure: always

